#!/bin/bash

cleanup() {
  echo "shutting down upstreams"
}

trap 'trap " " SIGTERM; kill 0; wait; cleanup' SIGINT SIGTERM

rm -rf server1 server2 server3 server4
mkdir -p server1 && touch server1/server1
mkdir -p server2 && touch server2/server2
mkdir -p server3 && touch server3/server3

python3 -m http.server --directory server1 8000 &
python3 -m http.server --directory server2 8001 &
python3 -m http.server --directory server3 8002 &
echo "Serving UDP on 0.0.0.0 port 8003 ..."
ncat -e "/bin/echo server4" -k -u -l 8003 &

wait